### ISSUE TITLE
Hey tyler, I need some help.

### ISSUE THREAD

**Issue by foxcqrn** [tylerhyperHD/EpiclyOPMod#1]
Sorry for this issue, it is not related to this repository in any way. This was the only way I could contact you @tylerhyperHD 

It's been awhile, and I've been practicing developing Java plugins ever since I learned from your tutorials on youtube. I would like to know if you could help me with an issue I've come across.

I own a survival server called FoxSurvival now, and it runs its own plugin called FoxSurvivalCore. It has a ranking system with a donator rank and I got the request to add a /color command to set automatic chat color to a players messages (i.e. /color red) For some reason, the plugin won't color the chat in that color. 

Here's the /color command:
https://pastebin.com/WBv12URk

Here's the ColorUtil:
https://pastebin.com/EzPD9r87

And here's the ChatColorListener:
https://pastebin.com/dXfHJqaP

I understand if you don't want to talk here, you can close this issue, but if you do close it, could you email me @ foxishdabest@gmail.com?

Thanks,
Dylan Fox

**Comment by tylerhyperHD** [comment]
I just changed it around, let me know if it works.

Color Command:
https://pastebin.com/jeCHxupc

ColorUtil:
https://pastebin.com/C3EAHMTj

Chat Color Listener:
https://pastebin.com/5XgyQ0YN

**Comment by foxcqrn** [comment]
That didn't work either.

**Comment by foxcqrn** [comment]
![image](https://user-images.githubusercontent.com/13877838/27256981-cc3664cc-537b-11e7-9c11-614d0ecc5744.png)

**Comment by tylerhyperHD** [comment]
It won't run with symbols like &c or stuff like that. Use /color purple or something

**Comment by foxcqrn** [comment]
I did /color yellow and then typed "hello" in the picture

![image](https://user-images.githubusercontent.com/13877838/27257310-5756fd96-5386-11e7-967e-8631c6bd68a7.png)

**Comment by tylerhyperHD** [comment]
Something must be setting your chat color then manually -- it's totally working on my end.

**Comment by foxcqrn** [comment]
Ok, I think I know the problem.

FoxSurvivalCore uses the player.setDisplayName(String); line to set the tags and colors for names.

So ```player.setDisplayName(ChatColor.GREEN + player.getName() + ChatColor.RESET);``` is how it sets it. I think the reset color is overriding the chat color.

Let me try something.

**Comment by foxcqrn** [comment]
Nevermind, I made the stupidest mistake of them all.
![image](https://user-images.githubusercontent.com/13877838/27462720-a3dc04aa-5777-11e7-91e6-6a4d0b4f5a83.png)
I forgot to add the ColorListener to the main file. **facepalm**

**Comment by foxcqrn** [comment]
Thanks for the help tyler ;P (BTW if you want to check out my server I'm using this on, apply at https://foxsurvival.github.io/apply you'll get instantly accepted.)

**Comment by tylerhyperHD** [comment]
lol

**Comment by foxcqrn** [comment]
I whitelisted you and the ip is on https://foxsurvival.github.io owo
